#%RAML 1.0
title: Starwars example API
description: Starwars example API
documentation:
 - title: Home
   content: !include api-doc.markdown
version: 1
protocols: [https]
baseUri: https://api.starwars.com/{version}

uses:
  Starwars: library/starwars-types.js

annotationTypes:
  experimental: boolean

securitySchemes:
  oauth_1_0:
    description: OAuth 1.0 is still supported
    type: OAuth 1.0
    settings:
      requestTokenUri: https://api.foobarbaz.com/1/oauth/request_token
      authorizationUri: https://www.foobarbaz.com/1/oauth/authorize
      tokenCredentialsUri: https://api.foobarbaz.com/1/oauth/access_token

resourceTypes:
  resourceCollection:
    usage: This resourceType should be used for any collection of items
    description: The collection of <<outputResource>>
    get:
      description: Get all <<outputResource>>, optionally filtered
      responses:
        200:
          body:
            application/json:
              type: <<outputResource>>[]

  singleResource:
    usage: This resourceType should be used for any collection of items
    description: The <<outputResource>>
    get:
      description: Get single <<outputResource>>
      responses:
        200:
          body:
            application/json:
              type: <<outputResource>>
    post:
      description: Create a new <<inputResource | !singularize>>
      body:
        application/json:
          type: <<inputResource>>
      responses:
        200:
          body:
            application/json:
              type: <<outputResource>>

traits:
  secured:
    usage: Apply this to any method that needs to be secured
    description: Some requests require authentication.
    headers:
      access_token:
        description: Access Token
        example: 5757gh76
        required: true

types:
  lat-long: # lat & long required; mutually exclusive with location
    properties:
      lat: number
      long: number
  loc: # location required; mutually exclusive with lat & long
    properties:
      location:
  paging: # each is optional, not exclusive with anything
    properties:
      start?: number
      page-size?: number

  !include_all ./types/**/*

securedBy: [oauth_1_0]

!resources ./api
